export const FETCH_NEWS_BY_SOURCE_REQUEST = "FETCH_NEWS_BY_SOURCE_REQUEST";
export const FETCH_NEWS_BY_SOURCE_SUCCESS = "FETCH_NEWS_BY_SOURCE_SUCCESS";
export const FETCH_NEWS_BY_SOURCE_FAILURE = "FETCH_NEWS_BY_SOURCE_FAILURE";
