export const FETCH_TOP_STORIES_REQUEST = "FETCH_TOP_STORIES_REQUEST";
export const FETCH_TOP_STORIES_SUCCESS = "FETCH_TOP_STORIES_SUCCESS";
export const FETCH_TOP_STORIES_FAILURE = "FETCH_TOP_STORIES_FAILURE";
