export const FETCH_NEWS_BY_CATEGORY_REQUEST = "FETCH_NEWS_BY_CATEGORY_REQUEST";
export const FETCH_NEWS_BY_CATEGORY_SUCCESS = "FETCH_NEWS_BY_CATEGORY_SUCCESS";
export const FETCH_NEWS_BY_CATEGORY_FAILURE = "FETCH_NEWS_BY_CATEGORY_FAILURE";
