export const FETCH_DEFAULT_QUERY_REQUEST = "FETCH_DEFAULT_QUERY_REQUEST";
export const FETCH_DEFAULT_QUERY_SUCCESS = "FETCH_DEFAULT_QUERY_SUCCESS";
export const FETCH_DEFAULT_QUERY_FAILURE = "FETCH_DEFAULT_QUERY_FAILURE";
