export const FETCH_TOP_STORIES_INDIA_REQUEST = "FETCH_TOP_STORIES_INDIA_REQUEST";
export const FETCH_TOP_STORIES_INDIA_SUCCESS = "FETCH_TOP_STORIES_INDIA_SUCCESS";
export const FETCH_TOP_STORIES_INDIA_FAILURE = "FETCH_TOP_STORIES_INDIA_FAILURE";
